### ISSUE TITLE
Broadcast Transaction Error:tx-sapling-active

### ISSUE THREAD

**Issue by Wangmmx** [RunOnFlux/fluxd#143]
What does the error means? And how can I solve that? 
Looking forward to your reply

**Comment by TheTrunk** [comment]
You are trying to construct transaction that is not compatible with current networking rules. So most likely your tx is not correct version, has bad branchid, is not overwintered.
Try using this library: https://github.com/ZelCore-io/bitgo-utxo-lib for a zelcash coin.

**Comment by Wangmmx** [comment]
Ok, I will try again. I refer to this for constructing transactions and signing:
https://github.com/zelcash/zelcashjs

I didn’t find the npm library of zelcashjs, I used the offline code assembly directly

**Comment by TheTrunk** [comment]
Oh yeah sorry, please do not use the library. It is obsolete and will not result in correct transactions. I just archived it for clarity now
You can use the bitgo-utxo-lib above in similar way to this:
```
const network = bitgotx.networks.zelcash;
const txb = new bitgotx.TransactionBuilder(network, maxFeeRate);
txb.setVersion(4);
txb.setExpiryHeight(expiryHeight);
txb.setVersionGroupId(0x892F2085);
txb.setLockTime(lockTime);
txb.addInput(x.txid, x.vout));
txb.addOutput(x.address, x.satoshis));
const keyPair = bitgotx.ECPair.fromWIF(senderPrivateKeyWIF, network);
const hashType = bitgotx.Transaction.SIGHASH_ALL;
txb.sign(input, keyPair, redeemscript, hashType, value, witnessscript);
const result = txb.build();
txHexString = result.toHex();
```
And you have raw signed tx that you can broadcast to a node

Please also refer to this real code examples:
https://github.com/TheTrunk/ZELmultisig/blob/development/src/App.vue#L218
https://github.com/zelcash/myzel/blob/development/app/components/wallet.jsx#L664

**Comment by Wangmmx** [comment]
Okay then I will try again, thanks

**Comment by blondfrogs** [comment]
@Wangmmx Is this still a problem? Can we close this issue?

**Comment by blondfrogs** [comment]
Closing as no responsive from @Wangmmx
