### ISSUE TITLE
Update old rpc calls using push_back to newer pushKV 

### ISSUE THREAD

**Issue by blondfrogs** [RunOnFlux/fluxd#170]
Most of the current rpc calls are using older code that code be updated. 

The rpc files are listed in /src/rpc

This only works on UniValue::VOBJ objects 

e.g  `info.push_back(std::make_pair("collateral", data.collateralIn.ToFullString())); ` ->    `info.pushKV("collateral", data.collateralIn.ToFullString());`

**Comment by w2vy** [comment]
I assume this is to improve readability of the code.

I see other places where the object (eg 'info') is Univalue, but std::make_pair is not used, should those be changed too?

rpc/zelnode.cpp line 1211
            UniValue info(UniValue::VOBJ);
            info.push_back(Pair("alias", zelnode.getAlias()));

**Comment by w2vy** [comment]
I needed to add a new pushKV function to handle (string, uint32_t)

**Comment by w2vy** [comment]
Ran gtest, same results as with master

```[==========] 194 tests from 32 test cases ran. (102904 ms total)
[  PASSED  ] 191 tests.
[  FAILED  ] 3 tests, listed below:
[  FAILED  ] checktransaction_tests.bad_txns_invalid_joinsplit_signature
[  FAILED  ] checktransaction_tests.non_canonical_ed25519_signature
[  FAILED  ] checktransaction_tests.OverwinterNotActive
```

**Comment by blondfrogs** [comment]
Added in #174
