### ISSUE TITLE
Rename code references zel, zelcash, zelnode to flux

### ISSUE THREAD

**Issue by blondfrogs** [RunOnFlux/fluxd#171]
There is a lot of code that uses this older names in the file name, objects, classes, comments. Are we need to update them to be flux. 

Do not update RPC names as they are used by explores, exchanges, mining pools, and others.  Instead, you can add a new RPC call that calls the older one. So we would have two RPC calls that do the same thing. One with updated naming scheme. 

An example in the code where an RPC call was added is in rpc/zelnode.cpp, here you can see the rpc call listzelnodes which was the old name, now calls the new name `viewdeterministiczelnodelist`.

`
UniValue listzelnodes(const UniValue& params, bool fHelp)
{
    return viewdeterministiczelnodelist(params, fHelp);
}
`

**Comment by w2vy** [comment]
So when adding flux tagged rpc call names, it looks like I duplicate these table entries and change the added line to 'flux"

static const CRPCCommand commands[] =
        { //  category              name                      actor (function)         okSafeMode
                //  --------------------- ------------------------  -----------------------  ----------
                { "zelnode",    "createzelnodekey",       &createzelnodekey,       false  },
                { "zelnode",    "getzelnodeoutputs",      &getzelnodeoutputs,      false  },
                { "zelnode",    "startzelnode",           &startzelnode,           false  },
                { "zelnode",    "listzelnodes",           &listzelnodes,           false  },

  ie add lines like this and add the appropriate wrapper functions 
                { "fluxnode",    "listfluxnodes",           &listfluxnodes,           false  },

**Comment by w2vy** [comment]
changing zelcash touches **a lot** of things!

I worry about name collision if I change zelcash to flux with no suffix.
Maybe fluxcash to rename but honor the history (yeah a bit philosophical)
or fluxXXX where XXX is anything that may make more sense.

**Comment by w2vy** [comment]
@blondfrogs Is the next step here to have the binaries build with the flux variant names?

**Comment by blondfrogs** [comment]
Yes. That is correct!

**Comment by w2vy** [comment]
@Cabecinha84 or @XK4MiLX could you checkout the zel2flux-bin-171 branch and build.
It has the binaries renamed to flux instead of zel

What other things do I need to change to simplify the deployment process?

**Comment by w2vy** [comment]
The binaries are now named properly and passed travis CI pipe https://app.travis-ci.com/github/RunOnFlux/fluxd/builds/250602308

What is the next step in deployment after these binaries are built?
There is someplace where they rename zelcashd to fluxd etc
@blondfrogs @Cabecinha84 @XK4MiLX

**Comment by Cabecinha84** [comment]
If they are already named properly you can test them easily by putting them
on a fluxnode and check if they work properly. Nothing else is needed, just
testing them.
Cheers

**Comment by w2vy** [comment]
I have new fluxd, flux-tx and flux-cli running on my testnet node, tomorrow after my cumulus pays out i'll put the binaries on it

**Comment by w2vy** [comment]
new binaries running on live node

**Comment by w2vy** [comment]
Running fine on my node, what and who takes next step?

**Comment by blondfrogs** [comment]
Fixed in release v6.1.0
#205
