### ISSUE TITLE
Go through and remove redundant if (IsDZelnodeActive()) checks

### ISSUE THREAD

**Issue by blondfrogs** [RunOnFlux/fluxd#173]
Now that deterministic zelnodes is active on mainnet for a while. Some places don't need to check if it is active anymore. 

This include rpc calls, and some consensus code. We should be careful when removing this check as in some places if could save time while syncing blocks earlier in the chain.

**Comment by w2vy** [comment]
In the current master there are no references to IsDZelnodeActive, this issue can be closed

**Comment by blondfrogs** [comment]
@w2vy what about IsDFluxnodeActive?

**Comment by w2vy** [comment]
Good point, those I will look at to understand better and then we can talk about which can go.

**Comment by w2vy** [comment]
@blondfrogs 
I reviewed all the IsDFluxnodeActive calls and they are all inside src/rpc/zelnode.cpp and defined in src/zelnode/zelnode.cpp

I went back to v5.2.0 (before I touched anything) and the instances of IsDZelnodeActive were the same.

I do see in main.cpp (ConnectBlock), miner.cpp (CreateNewBlock) and zelnode.cpp (rebuildfluxnodedb) 
where the block height is compared to StartFluxnodePayments

So it seems IsDFluxnodeActive is only used in the RPC calls.

**Comment by blondfrogs** [comment]
@w2vy That sounds correct. Lets get together and see if we need them anymore.

**Comment by w2vy** [comment]
closed with PR#192
