### ISSUE TITLE
Need to update Copyright message

### ISSUE THREAD

**Issue by w2vy** [RunOnFlux/fluxd#176]
Found this in mining.ccp
// Copyright (c) 2019 The Zelcash Core developers

Looks at other files and found no mention of Zelcash or Flux developers
Should we add a copyright message to everything we have changed?

**Comment by blondfrogs** [comment]
@w2vy Yes we should add a copy write to everything we have changed. It wouldn't be a bad thing to add it to all files if it doesn't exist. I am pretty sure there is a tool that will do this for us located in. /zelcash/contrib/devtools/fix-copyright-headers.py

**Comment by w2vy** [comment]
Ok many files have copyright as
```// Copyright (c) 2009-2012 The Bitcoin developers
// Copyright (c) 2015-2019 The PIVX developers
// Copyright (c) 2018-2019 The Zel developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://www.opensource.org/licenses/mit-license.php.
```
Are we leaving that as Zel developers for now?

**Comment by w2vy** [comment]
@blondfrogs 
I found some older files that used "The Flux Developers" so I started using that.
I just noticed that the snapshotdb files (c,h) used "The Flux Core Developers"

Any preference?

I attached a file with many with no copyright and many with people, etc. [need_attention.txt](https://github.com/RunOnFlux/fluxd/files/8553863/need_attention.txt)

I could see which we have modified, maybe assume anything with a git time > 3 years is unmodified by us and skip adding the copyright?

**Comment by w2vy** [comment]
I resolved the questions.

I skipped the 3 directories that had either a LICENSE file or COPYING file, indicating another license was in place.
All other files either had No License/copyright or the MIT license

To those files I added or updated the MIT header

**Comment by blondfrogs** [comment]
@w2vy Sounds good
