### ISSUE TITLE
Build problem Ubuntu 21.10

### ISSUE THREAD

**Issue by w2vy** [RunOnFlux/fluxd#180]
May apply to other versions, but it did build fine on docker image of 20.04

I found two issues and need help properly applying them to the code base

**Comment by w2vy** [comment]
First problem I found was same as https://github.com/zcash/zcash/issues/4354
I manually applied the change and the patch warning went away

The next error was identical to http://github.com/boostorg/thread/issues/283 and repaired by https://github.com/boostorg/thread/pull/297

**Comment by w2vy** [comment]
@blondfrogs I was wrong about the last change being local, boostorg issue 283 above, it is in the downloaded boost
tom@rnode:~/fluxd-vol/fluxd$ find . -name thread_data.hpp
./depends/x86_64-unknown-linux-gnu/include/boost/thread/pthread/thread_data.hpp
./depends/x86_64-unknown-linux-gnu/include/boost/thread/win32/thread_data.hpp

So I guess we need to patch the patch or use a newer version of boost that has this fix.

**Comment by blondfrogs** [comment]
@w2vy Do we know which version of boost has this fix?
