### ISSUE TITLE
librustzcash.h missing

### ISSUE THREAD

**Issue by FndNur1Labs** [RunOnFlux/fluxd#184]
missing librustzcash.h can you guys help
![Screenshot from 2022-03-23 20-22-10](https://user-images.githubusercontent.com/11433397/159709337-e463545d-9701-4699-a357-5474454435d8.png)

**Comment by w2vy** [comment]
It should be here depends/x86_64-unknown-linux-gnu/include/librustzcash.h
go to the fluxd directory and do a find . -name librustzcash.h

What target are you running on?
What OS Version?
Some details might help

**Comment by FndNur1Labs** [comment]
> It should be here depends/x86_64-unknown-linux-gnu/include/librustzcash.h
> go to the fluxd directory and do a find . -name librustzcash.h
> 
> What target are you running on?
> What OS Version?
> Some details might help

Debian 10. I already install depency and all fine when make not working like below

**Comment by blondfrogs** [comment]
@FndNur1Labs Can we close this issue?

**Comment by blondfrogs** [comment]
Closing Issue as no response in 4 months.
