### ISSUE TITLE
Crash after submitting a new block

### ISSUE THREAD

**Issue by Ewemek** [RunOnFlux/fluxd#209]
At height 1280555, one of our node crashed with the following logs:
```
09:47:54.683 CreateNewBlock(): total size 55111
09:47:54.717 CreateNewBlock(): total size 55111
09:48:20.965 receive version message: /flux_seeder:1.00/: version 170018, blocks=1000000, us=********:16125, peer=579362
09:48:36.707 ERROR: Flush - 812 , Found map:at error
```
It happens that we were submitting a block to this node at the exact same second of the crash, so it might be the trigger of the error.

**Comment by blondfrogs** [comment]
@Ewemek Can you confirm the version on fluxd you are using on the node that is crashing?

**Comment by Ewemek** [comment]
We're on v6.0.0 since we started mining

**Comment by blondfrogs** [comment]
@Ewemek We are still working on finding the exact cause for this error. Once the latest version v6.1.0 is released it will contain a lot more logging when an error like this is throw. If you could please update to v6.1.0 when it is released that would help a lot.

**Comment by Ewemek** [comment]
Thanks, looking forward to this new version, this problems happens 2 times a month, so it's kinda rare, but I'm sure we will be able to provide some logs.

**Comment by blondfrogs** [comment]
@Ewemek Awesome. More logs is good for us

**Comment by Ewemek** [comment]
I saw that you created some tags, but reverted, will you communicate when the new version is ready ?

**Comment by blondfrogs** [comment]
@Ewemek v6.1.0 is available.

**Comment by blondfrogs** [comment]
@Ewemek Could you give us the full log file?

**Comment by Ewemek** [comment]
[fluxd-flush-crash-log-20230227.txt](https://github.com/RunOnFlux/fluxd/files/10880196/fluxd-flush-crash-log-20230227.txt)
Here are the 10 last hours of logs, if you need more, can you tell me until which height I must go back ? Because exporting our logs in painful and it needs some preparation.

**Comment by blondfrogs** [comment]
@Ewemek You are more than welcome to try our pre-release build which includes some changes I made to hopefully stop the crash: 

https://github.com/RunOnFlux/fluxd/releases/tag/v6.1.0-debug-1

**Comment by Ewemek** [comment]
Hi, we will update some of our node with it probably this week. We'll keep you posted

**Comment by Ewemek** [comment]
Not at all for the moment, but the frequency was like 1 occurrence every 2 or 3 weeks, we just happened to encounter it twice during the same week last time
is there a specific log that I could search for to know if problem should have happened but did not thanks to the fix ?

**Comment by blondfrogs** [comment]
@cryptooliko Thank you for letting me know. 

Was this a pools daemon that crashed?

**Comment by Ewemek** [comment]
Hi @blondfrogs, the problem didn't happen at all in almost one month, I guess the problem is solved.

**Comment by blondfrogs** [comment]
@Ewemek That is great to hear. I am going to leave this issue up for another month or so to make sure.

**Comment by blondfrogs** [comment]
@Ewemek @cryptooliko Please use version 6.2.0 that was just released. You can find it on the releases section of github. Hopefully this bug will not occur anymore.

**Comment by blondfrogs** [comment]
@cryptooliko @Ewemek v7.0.1 Fixes all of the above issues. If more issues present themselves please create a new ticket with the details.
