### ISSUE TITLE
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://zelcash.github.io/aptrepo all InRelease' doesn't support architecture 'i386'

### ISSUE THREAD

**Issue by banshen** [RunOnFlux/fluxd#99]
sudo apt-get update
N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'https://zelcash.github.io/aptrepo all InRelease' doesn't support architecture 'i386'

**Comment by blondfrogs** [comment]
Closing - No updated response. Considered solved.
